name: End2EndTests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latest
        python-version: "3.8"

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies and Package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[all]
        python -m pip install sphinx
    - name: Build docs
      working-directory: ./docs/
      run: |
        make html
