name: Unittests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        # Python 3.6 is not available in the ubuntu-latest container github
        # provides, so skip that configuration.
        exclude:
          - os: ubuntu-latest
            python-version: "3.6"
        # Python 3.6 is still in the ubuntu-20.04 container from github so
        # test git-theta in that container instead.
        include:
          - os: "ubuntu-20.04"
            python-version: "3.6"

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies and Package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test,pytorch]
    - name: Run Unit Tests
      run: |
        pytest
