name: Unittests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      max-parallel: 12
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: "setup.py"
    - name: Install Dependencies and Package
      run: |
        python -m pip install --upgrade pip
        # Install pinned deps when testing to avoid backtracking
        python -m pip install -r requirements-ci.txt
        python -m pip install .[test,all]
    - name: Run Unit Tests
      run: |
        pytest
